### ISSUE TITLE
PhoneGap project is discontinued, please update docs

### ISSUE THREAD

**Issue by macrel** [mendix/hybrid-app-template#39]
As of 1 oktober 2020 the PhoneGap build service is no longer available. Also PhoneGap will no longer be actively developed.

Please update the hybrid-app-template and documentation according to these changes with alternative tools / procedures. 

Source: https://blog.phonegap.com/update-for-customers-using-phonegap-and-phonegap-build-cc701c77502c

**Comment by macrel** [comment]
Ps. maybe this is something to look into: https://ionicframework.com/appflow

**Comment by florisdg** [comment]
We are running into similar issues here, I'm going to create a support ticket about these problems as well. @macrel could you keep me updated when you get a reply on the forums or have learn anything? I'll do the same for you.

I've spent hours to find out why we couldn't upload any photo(or any file) using our iOS and Android apps which are both published in their corresponding app stores. First we just assumed the DropZone widget was buggy but when we tried the FileDropper widget the same error occured (net::ERR_FILE_NOT_FOUND whenever it wanted to do a HTTP POST request).
After that I went digging in our PhoneGap package and found out the majority of it's dependencies  are out-of-date. The most important ones being cordova-android, cordova-ios and a lot of the cordova-plugin-* packages as well. 
I honestly wish I discovered this earlier because all work the work we put into getting the apps in the stores has been for naught!

**Comment by macrel** [comment]
Hi, thanks for your update. I will keep you posted if I learn more. Mendix has to take action on this that's for sure!

**Comment by dannyroestmx** [comment]
We are working on updating the documentation, source code and the platform to reflect the shutdown of PhoneGap.

Overall our focus is on Native Mobile and PWA as in general the market is leaving Hybrid. More details on this will soon follow.

@florisdg Our apologies for the inconvenience. We do not actively update the versions of the libraries unless needed (as upgraden could also causes other issues). Also, we didd not test with the mentioned widget as these are not platform supported. If you do run into issues, feel free to reach out to support

**Comment by florisdg** [comment]
> ... 
> @florisdg Our apologies for the inconvenience. We do not actively update the versions of the libraries unless needed (as upgraden could also causes other issues). Also, we didd not test with the mentioned widget as these are not platform supported. If you do run into issues, feel free to reach out to support

Hi, and sorry @dannyroestmx, no need to apologize! I didn't realize I was venting like that in my previous post. I have created a support ticket(ticket #107264) with Mendix and also referenced this issue in there.

> Note that overall our focus is on Native Mobile and PWA as in general the market is leaving Hybrid. More details on this will soon follow.

Will this be included in the Studio Pro 9.0 release? Or will the webmodeler be pushed forward instead?

**Comment by smarki** [comment]
@florisdg  Mendix 8 has already Native Mobile included and we are working on simplifying the complexity of building native apps; similar to what Phonegap Build was offering but now for native apps. That second part is still planned for release with 8.15. 

PWA is work in progress and indeed all this of course will also be part of Studio Pro 9.0 which further enhances the dev experience. 

As Danny mentioned; the best way to get any issues or concerns handled is the official Mendix support. 

I am closing the issue for now.
